### ISSUE TITLE
Dapper?

### ISSUE THREAD

**Issue by schmitch** [mishael-o/Dapper.SimpleSqlBuilder#28]
### Feature request type

Other

### Describe the solution you would like

I stumbled upon your library and have a simple question, does your library even need dapper that much? it looks like you only use `DynamicParameters` wouldn't it make more sense to have a small library like Dapper.SimpleSqlBuilder.Integration which implicitly converts from `YourDynamicParameters` to `Dapper's DynamicParameters`? your library basically is so good that it should not be tied to dapper ;)

### Pull Request

- [ ] I would like to do a Pull Request

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mishael-o** [comment]
@schmitch thanks for the feedback. 

I do see your point as the library could return its own `Parameters` and not use Dapper's `DynamicParameters`. However, there are some features that are used from Dapper's `DynamicParameters` like `Get<T>(...)` and `AddDynamicParams(...)`. 

As for the `Dapper.SimpleSqlBuilder.Integration` idea, I wouldn't want consumers of the library to incur the extra memory cost of converting from `Parameters` to Dapper's `DynamicParameters`, as I want the library to be fast and efficient.

I could in essence decouple Dapper from the library but that will need a rewrite.

Do you have a user case where this will be beneficial for you?
