### ISSUE TITLE
ODBC parameter support

### ISSUE THREAD

**Issue by Laptop765** [mishael-o/Dapper.SimpleSqlBuilder#30]
### Feature request type

New feature

### Is your feature request related to a problem?

This is a super cool library! I was just playing around with it and found that it doesn't seem to work for `ODBC` data sources. I know it's an older technology so I understand if it ends up being a won't fix. [The way it treats parameters is very ugly](https://stackoverflow.com/a/18082957), using `?` with no differentiation between parameters. Sadly the way your library generates queries ends up being incompatible.

### Describe the solution you would like

Perhaps an option could be added for `ODBC` support: `SimpleBuilderSettings.Configure(parameterOdbcFormatting: true);`

Then when the query is generated instead of inserting `@p0`, `@p1`, etc. it uses `?`, `?`, etc. I only took a brief look at the code so I don't know how how simple this actually would end up being in practice.

### Describe alternatives you have considered

`SimpleBuilderSettings.Configure(parameterNameTemplate: string.Empty, parameterPrefix: "?");` is actually pretty close although I'm not sure the `string.Empty` is being respected. Regardless, the appended numbers will still cause a problem.

### Pull Request

- [ ] I would like to do a Pull Request

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Laptop765** [comment]
Right after I finished typing this I tried doing a `.Replace("@p0", "?")` on a simple query and that ended up working! I still wanted to post this for consideration but more to mention this workaround for anyone else who comes by looking for `ODBC` support.

**Comment by mishael-o** [comment]
Hi @Laptop765. Thanks for the feedback. Unfortunately, it will be difficult to support `ODBC` parameter as the library needs to know what parameter value corresponds to a parameter name to enable features like parameter reuse.

**Comment by Laptop765** [comment]
That's what I figured. I have a fairly simple case so I'll use my workaround which will hopefully work for anyone else stuck with `ODBC` 😀
