### ISSUE TITLE
Any plans to separate the fluent APIs into a standalone project?

### ISSUE THREAD

**Issue by 1249993110** [mishael-o/Dapper.SimpleSqlBuilder#41]
### Feature request type

Other

### Is your feature request related to a problem?

Can `Normal Builder` and `Fluent Builder` be published projects to NuGet package separately as two projects? I think sometimes people just want to use `Normal Builder`.

### Describe the solution you would like

Publish `Normal Builder` and `Fluent Builder` as standalone NuGet package.

### Pull Request

- [ ] I would like to do a Pull Request

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mishael-o** [comment]
Hi @1249993110, thanks for the feedback. There is no plan to publish the `Builder` and `Fluent Builder` as separate NuGet packages, as this would be extra effort and work, and I don't think it is worth it. 

You can ignore or not use the `Fluent Builder` if doesn't provide value to you, however, it beneficial for other users who use both, so they don't have to add an extra package.

**Comment by 1249993110** [comment]
Thank you very much for your reply, I understand.
